// The generated `pi-bg` CLI: a POSIX shell wrapper plus the Node client it
// delegates to.
//
// One surface, declared:
//
//   * `get|list|stop` are the operations. They cannot be answered from the
//     filesystem — readiness, the review clock, and a confirmed stop live in the
//     manager — so they are sent over the session-private socket from
//     `bridge.ts`.
//
// The former `path|peek|read` log-file helpers are gone. They read the live log
// straight off disk, which bypassed the completion acknowledgment entirely
// (`read` even cleared the exit wake from another channel), so the wrapper now
// answers them with a migration error rather than quietly handing back a log the
// manager has not certified.
//
// The client is a plain Node program rather than a shell one because a POSIX
// shell cannot open a Unix socket without an extra tool, and because the
// handoff needs to control write completion and EPIPE precisely. It imports
// nothing outside `node:` builtins, so the only requirement is the runtime
// already present on the host: the wrapper prefers `bun` (Pi's own runtime),
// then `node`, and `PI_BG_RUNTIME` overrides both.
//
// The client speaks the same protocol as `bridge.ts` but holds its own small
// copy of the framing: it is written to disk as a standalone file, so it cannot
// import the extension's modules.

export const PI_BG_CLIENT_FILE = "pi-bg-client.mjs";

/** Exit codes the client and wrapper agree on. */
export const PI_BG_EXIT = {
	/** The requested operation completed and the output handoff finished. */
	ok: 0,
	/** A management failure: no such task, stale generation, expired handle,
	 *  an unconfirmed stop, or a capture that cannot be certified complete. */
	failure: 1,
	/** The command line was not a valid `pi-bg` request. */
	usage: 2,
	/** The session's endpoint is not reachable from this environment. */
	unavailable: 3,
} as const;

/** The shell wrapper installed as `pi-bg`. */
export function piBgWrapperScript(): string {
	return `#!/usr/bin/env bash
# kendex declared background-task CLI.
#
#   pi-bg get <task-id>          task state, readiness, and an output preview
#   pi-bg list                   running and finished tasks in this session
#   pi-bg stop <task-id>         stop a task and report the confirmed result
#
set -uo pipefail
usage() {
	cat >&2 <<'USAGE'
usage: pi-bg get <task-id> [--output]
       pi-bg list
       pi-bg stop <task-id>
USAGE
	exit 2
}
# A retired live-path helper. Reading a task's log file directly would bypass the
# completion acknowledgment (the result is only certified once the manager has
# settled its capture), so it is refused with the operation that replaces it
# instead of quietly returning a file the manager has not certified.
retired() {
	cat >&2 <<'RETIRED'
pi-bg: the log-file helpers (path, peek, read) were removed: they read a task's live log
        directly, which bypassed completion acknowledgment. Use:
          pi-bg get <task-id>            the task's result, readiness, and output preview
          pi-bg get <task-id> --output   the complete immutable captured snapshot on stdout
          pi-bg list                     running and finished tasks in this session
          pi-bg stop <task-id>           stop a task and report the confirmed result
RETIRED
	exit 2
}
client() {
	# The client sits beside this wrapper, so a PATH lookup still finds it.
	local here runtime
	here="$(cd "$(dirname "$0")" && pwd)"
	runtime="\${PI_BG_RUNTIME:-}"
	if [ -z "$runtime" ]; then
		if command -v bun >/dev/null 2>&1; then runtime=bun
		elif command -v node >/dev/null 2>&1; then runtime=node
		fi
	fi
	if [ -z "$runtime" ]; then
		echo "pi-bg: no bun or node interpreter found; set PI_BG_RUNTIME to one" >&2
		exit 3
	fi
	exec "$runtime" "$here/${PI_BG_CLIENT_FILE}" "$@"
}
cmd="\${1:-}"; [ -n "$cmd" ] || usage; shift || true
case "$cmd" in
	path|peek|read) retired ;;
	get|list|stop) client "$cmd" "$@" ;;
	*) usage ;;
esac
`;
}

/**
 * The standalone Node client. Bounded waits, explicit exit codes, stdout for
 * payload and stderr for metadata: the requested write has to finish before the
 * command reports success, because that report is what the caller's receipt
 * depends on.
 */
export function piBgClientSource(): string {
	return `#!/usr/bin/env node
// Generated by @vanillagreen/pi-background-tasks. Do not edit: it is rewritten
// whenever the extension installs its managed-shell shims.
import { createReadStream } from "node:fs";
import { connect } from "node:net";
import process from "node:process";

const PROTOCOL = 1;
const MAX_RESPONSE_BYTES = 4 * 1024 * 1024;
const TIMEOUT_MS = Number(process.env.PI_BG_TIMEOUT_MS || 5000);
const EXIT = { ok: 0, failure: 1, usage: 2, unavailable: 3 };

const usage = () => {
	process.stderr.write("usage: pi-bg get <task-id> [--output]\\n       pi-bg list\\n       pi-bg stop <task-id>\\n");
	process.exit(EXIT.usage);
};

const meta = (fields) => {
	for (const [key, value] of Object.entries(fields)) {
		if (value === undefined || value === null || value === "") continue;
		process.stderr.write("kendex: " + key + "=" + value + "\\n");
	}
};

// A closed pipe is a failed handoff, not a crash: report it and exit non-zero
// so the manager never commits a receipt for output nobody received.
let pipeFailure = null;
process.stdout.on("error", (error) => {
	pipeFailure = error;
	meta({ result: "error", code: error.code === "EPIPE" ? "epipe" : "write-failed", detail: error.message });
	process.exit(EXIT.failure);
});

const socketPath = process.env.PI_BG_SOCKET;
if (!socketPath) {
	process.stderr.write("pi-bg: PI_BG_SOCKET is not set; run this from a managed command of the owning session\\n");
	process.exit(EXIT.unavailable);
}

const argv = process.argv.slice(2);
const op = argv[0];
if (!op) usage();
let id = null;
let output = "preview";
if (op === "get" || op === "stop") {
	id = argv[1] && !argv[1].startsWith("-") ? argv[1] : null;
	if (!id) usage();
	for (const arg of argv.slice(2)) {
		if (arg === "--output") output = "full";
		else usage();
	}
} else if (op === "list") {
	if (argv[1]) usage();
} else usage();

/** One request, one response. Resolves an outcome; it never throws, because a
 *  silent or unreachable endpoint has to be reported rather than guessed at. */
function request(payload) {
	return new Promise((resolve) => {
		let settled = false;
		let buffer = "";
		const socket = connect(socketPath);
		const finish = (outcome) => {
			if (settled) return;
			settled = true;
			clearTimeout(timer);
			socket.destroy();
			resolve(outcome);
		};
		const timer = setTimeout(() => finish({ ok: false, error: { code: "unavailable", message: "endpoint did not answer within " + TIMEOUT_MS + "ms" } }), TIMEOUT_MS);
		socket.setEncoding("utf8");
		socket.on("error", (error) => finish({ ok: false, error: { code: "unavailable", message: "endpoint " + socketPath + " unavailable: " + error.message } }));
		socket.on("close", () => finish({ ok: false, error: { code: "malformed", message: "endpoint closed without a response" } }));
		socket.on("data", (chunk) => {
			buffer += chunk;
			if (buffer.length > MAX_RESPONSE_BYTES) {
				finish({ ok: false, error: { code: "malformed", message: "endpoint response exceeds the client cap" } });
				return;
			}
			const newline = buffer.indexOf("\\n");
			if (newline === -1) return;
			try {
				const parsed = JSON.parse(buffer.slice(0, newline));
				if (parsed && parsed.ok === true) finish({ ok: true, response: parsed });
				else finish({ ok: false, error: (parsed && parsed.error) || { code: "malformed", message: "endpoint response is malformed" } });
			} catch (error) {
				finish({ ok: false, error: { code: "malformed", message: "endpoint response is not JSON: " + error.message } });
			}
		});
		socket.on("connect", () => socket.write(JSON.stringify({ v: PROTOCOL, session: process.env.PI_BG_SESSION, ...payload }) + "\\n"));
	});
}

function fail(error) {
	meta({ result: "error", code: error.code, detail: error.message });
	process.exit(error.code === "unavailable" ? EXIT.unavailable : EXIT.failure);
}

function describeTask(task) {
	meta({
		task: task.id,
		generation: task.generation,
		status: task.status,
		readiness: task.readiness,
		pid: task.pid,
		command: task.command,
		outputBytes: task.outputBytes,
		captureComplete: task.outputComplete,
	});
}

/**
 * Write a preview to stdout and resolve once the write has been flushed. The
 * callback is the difference between "handed to the OS" and "handed over":
 * reporting success on the call's return would commit the receipt while the
 * last bytes are still buffered.
 */
function writeText(text) {
	return new Promise((resolve) => {
		if (!text) return resolve({ ok: true });
		process.stdout.write(text, (error) => {
			if (error) return resolve({ ok: false, error: { code: error.code === "EPIPE" ? "epipe" : "write-failed", message: error.message } });
			// A pipe that closed while this write was in flight is reported by the
			// stdout error handler; treat that as the failure it is.
			if (pipeFailure) return resolve({ ok: false, error: { code: "epipe", message: pipeFailure.message } });
			resolve({ ok: true });
		});
	});
}

/**
 * Stream a retained snapshot to stdout and resolve only after every chunk has
 * been flushed to the file descriptor. Resolving on the read's end would report
 * success while the last bytes are still buffered, which is exactly the
 * difference the receipt commit depends on.
 */
function streamFile(path) {
	return new Promise((resolve) => {
		let outstanding = 0;
		let ended = false;
		let settled = false;
		const done = () => {
			if (settled || !ended || outstanding > 0) return;
			settled = true;
			resolve({ ok: true });
		};
		const fail = (message, code) => {
			if (settled) return;
			settled = true;
			resolve({ ok: false, error: { code: code || "internal", message } });
		};
		const source = createReadStream(path);
		source.on("error", (error) => fail("snapshot unreadable: " + error.message, "expired"));
		source.on("data", (chunk) => {
			outstanding += 1;
			source.pause();
			process.stdout.write(chunk, (error) => {
				outstanding -= 1;
				if (error) return fail("snapshot write failed: " + error.message, error.code === "EPIPE" ? "epipe" : "write-failed");
				if (!pipeFailure) source.resume();
				done();
			});
		});
		source.on("end", () => {
			ended = true;
			done();
		});
	});
}

/**
 * Accept the prepared-result receipt. Sent only after the requested output
 * handoff finished, and only for a handoff that was a complete result: an
 * uncertified capture hands its bytes over but must not look settled. A token
 * the manager already accepted is replayed, so a dropped connection is
 * retryable without a second acknowledgment.
 */
async function acceptReceipt(token) {
	const outcome = await request({ op: "receipt", token });
	if (!outcome.ok) {
		meta({ result: "error", code: outcome.error.code, detail: outcome.error.message });
		return false;
	}
	const ack = (outcome.response.result && outcome.response.result.ack) || {};
	// Report what the handoff actually settled: a boolean could not distinguish
	// a review reset from a completion acknowledgment.
	meta({ ack: ack.committed || "none" });
	return true;
}

const run = async () => {
	const outcome = await request(op === "list" ? { op } : { op, id, output });
	if (!outcome.ok) return fail(outcome.error);
	const { response } = outcome;
	if (op === "list") {
		const tasks = response.result.tasks || [];
		for (const task of tasks) {
			process.stdout.write([task.id, task.status, task.readiness, task.outputComplete ? "complete" : "incomplete", task.command].join("\\t") + "\\n");
		}
		meta({ result: "ok", tasks: tasks.length, session: response.session });
		return EXIT.ok;
	}
	const task = response.result.task;
	if (task) describeTask(task);
	const captureError = response.result.captureError;
	if (captureError) meta({ result: "capture-incomplete", detail: captureError });

	// Hand the output over first, and only then decide whether the obligation
	// may be settled.
	const handoffOutput = response.result.output;
	let handoff = { ok: true };
	if (handoffOutput && handoffOutput.kind === "preview") handoff = await writeText(handoffOutput.text);
	else if (handoffOutput && handoffOutput.kind === "snapshot") handoff = await streamFile(handoffOutput.path);
	if (!handoff.ok) return fail(handoff.error);

	// An uncertified capture is a management failure even though the partial
	// bytes above were handed over: the obligation must not look settled, so no
	// receipt is sent and none is committed.
	if (captureError) {
		meta({ result: "incomplete-capture", op, code: "capture-incomplete" });
		return EXIT.failure;
	}

	// The bytes are out. Only now is the prepared handoff settled.
	if (response.result.receipt) {
		if (!(await acceptReceipt(response.result.receipt))) return EXIT.failure;
	}
	meta({ result: "ok", op });
	return EXIT.ok;
};

run().then((code) => process.exit(code)).catch((error) => {
	meta({ result: "error", code: "internal", detail: error && error.message ? error.message : String(error) });
	process.exit(EXIT.failure);
});
`;
}
